### ISSUE TITLE
Interesting location choice!

### ISSUE THREAD

**Issue by mjotten1998** [teuteuf/worldle#100]
So it took me some time to figure out the worldle location today, even when using google maps after racking my brain for 20 minutes. The reason for this is neat though, because the worldle algorithm may have chosen the single hardest island location possible. The worldle today is a location that; contains no inhabitants (permanent or temporary), is not classified as a territory/dependency/special administration/etc, and is, by most accounts, the most remote island on earth (less than 100 people have ever been there). 

It is so remote that, after it was initially discovered in 1739, the island was LOST until it was rediscovered in 1808... then again in 1898... both times on accident. The most recent, publicly known time anyone has actually been to the island was in 2003. According to google the closest inhabited spot to this island is Tristan de Cunha Island (2250 km away) which itself is also in the middle of the Atlantic ocean and the closest inhabited spot to that is St. Helena which is 2490 km away!

This is a bit rambling at this point, but I enjoy worldle due to things like this. I never would heard of Bouvet Island without this website so thanks.

**Comment by dougaitken** [comment]
Spoilers for today but the Worldle for 12th March 2022 is still on the [ISO3166-1](https://en.m.wikipedia.org/wiki/ISO_3166-1) list so it’s valid. 

It’s also not chosen, it’s random.
