### ISSUE TITLE
Add Wikipedia link

### ISSUE THREAD

**Issue by RickABQ** [teuteuf/worldle#102]
Cool game, I’m enjoying it. I even like the ones like Bouvet Island!  I almost always look up the answer on Wikipedia afterwards. In addition to the Google maps link, I suggest you add a Wikipedia link once the puzzle is solved.  Make it a bit more of an educational experience!

**Comment by Lgrizzz** [comment]
Agreed!! Or even a few interesting facts about the country/territory!

**Comment by teuteuf** [comment]
Done! Wikipedia link added!
