### ISSUE TITLE
Image shown was for Terceira Island(not in the option) instead of Bouvet Island

### ISSUE THREAD

**Issue by lenirom** [teuteuf/worldle#104]
![20220313_013220_0000](https://user-images.githubusercontent.com/101472323/158028453-380eba59-eb3a-4892-bc0f-e9dcf86b5672.png)

**Comment by teuteuf** [comment]
yep, you're right, it has already been reported and fixed here: https://github.com/teuteuf/worldle/issues/94
you probably have the wrong image cached on your side, I need to improve the cache refresh.
