### ISSUE TITLE
Stop using ISO_3166-1, or at least cull the list 

### ISSUE THREAD

**Issue by SoulinaBowl** [teuteuf/worldle#107]
No one wants to guess Bouvet Island, British Indian Ocean Territory, and other uninhabited rocks. Every time, there's a dozen complaints, and your answer is just "It's on the list." In that case, the problem is the list. This should just be sovereign nations.

**Comment by apgove** [comment]
I disagree, the more obscure entries are what makes this fun, challenging, and educational.  Besides, there is no way to define "sovereign nations" without controversy, it's an unwinnable fight, a can of worms.  C.f. Taiwan, Palestine, Falklands...

**Comment by missmadmolly** [comment]
I definitely agree SoulinaBowl!!

**Comment by Tiv0w** [comment]
> No one wants to guess Bouvet Island, British Indian Ocean Territory, and other uninhabited rocks. Every time, there's a dozen complaints, and your answer is just "It's on the list." In that case, the problem is the list. This should just be sovereign nations.

There are many complaints, but there might be many more people being happy with the fact that you learn new things about our planet each day. And the people being satisfied by the game don't fill issues, so you can't really use the number of complaints as an argument.

And if you really want only an arbitrary country list you want to define, you should either create your own COUNTRYDLE (maybe fork the project), or propose a PR with a clear way to restrict the selection.

I'm grateful the project is as it is, and I wouldn't want it to be a restricted subset of what it is.

**Comment by teuteuf** [comment]
A lot of people like to discover this kind of tiny island too!
I understand it could have been quite frustrating because there were 2 very difficult picks in a row...
I check, the few incoming picks should be a bit easier!

I prefer to stick to this list, mostly for the reason pointed by @apgove.
