### ISSUE TITLE
100% but not correct

### ISSUE THREAD

**Issue by smcqwilson** [teuteuf/worldle#109]
Hello! Yesterday, I guessed Guernsey (27 miles away) and it gave me a 100% but I still needed to keep guessing to get the actual correct answer, Jersey. Wondering if you are able decrease the threshold to 0 miles to confirm a 100% correct answer. 
Love the game - thanks!!!

**Comment by smcqwilson** [comment]
![Uploading 9D460C3E-20E5-4AFD-B5C5-085DBE5CF847.jpeg…]()

**Comment by smcqwilson** [comment]
![5AB400B3-5CAB-43E1-A17C-3ACDE1C5B38D](https://user-images.githubusercontent.com/101485338/158040487-8fe5040c-2d80-4338-8a81-4d99ac223e6b.jpeg)

**Comment by teuteuf** [comment]
Already fixed, as soon as you cache get refreshed, it should not appear anymore! :)
