### ISSUE TITLE
Worldle infinite 

### ISSUE THREAD

**Issue by Cakewalker872** [teuteuf/worldle#114]
I absolutely love worldle, it's my favorite version of wordle and I play it ever day, so I was wondering if we could ever get an infinite version, or if that's not planned in the future.

**Comment by Irr0n** [comment]
ditto!

**Comment by Neerfix** [comment]
I work on this feature on my fork.

To wait it, you can play on : https://worldle-infinite--infinite-9bq0ndfx.web.app/

**Comment by teuteuf** [comment]
Haven't plan to add it in the game! I think the one puzzle a day is a important part of the fun of the game.
But you can use @Neerfix url to have random pick after each refresh or use some site like sporcle or seterra to practice. :)
I also have a training mode, a bit different, in mind but I need to find time to work on it...
