### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by mariondefnet** [teuteuf/worldle#115]
Love this game but I  am unable to share using the 'share' button on my iPhone 11 or my MacBook Pro. I am able to share Wordle and all the other word/math games using the share buttons. When I touch share, it says 'copied to clipboard'. Then I don't know where it is or how to share with my friends. 

![IMG_1653](https://user-images.githubusercontent.com/101651414/158402267-97c82760-20c2-49eb-bf7b-77cf6c8a6956.PNG)

**Comment by Cakewalker872** [comment]
When it says copied to clipboard you can paste it from there, just don't copy something else and paste it w

**Comment by teuteuf** [comment]
I hope @Cakewalker872 answer helped you! I close this issue, let me know if it's still not working.
