### ISSUE TITLE
Share using distance, direction, percent (and not wordle squares)

### ISSUE THREAD

**Issue by kewpiedoll99** [teuteuf/worldle#117]
I get it, the wordle squares are cute and fun and sort of bite off the wordle style to make the game au courant. But they aren't really useful as a mode of communication. What would be a much more useful share would be:

![Screen Shot 2022-03-16 at 9 40 52 AM](https://user-images.githubusercontent.com/7469541/158607571-6b16595e-218b-49f3-9e94-71f5852d25be.png)
That was mine, today, when I got very close but ultimately failed. 

Because I am playing the game on my laptop I can do a selective screen cap like the above and share that with my friends. We all agree it is more useful as a share. But a screen cap on a mobile will also include the correct answer, so if you share that it will be a spoiler.

Perhaps the 🎉 emoticon when you succeed, of course, because we all love a 🎉.

**Comment by Cakewalker872** [comment]
What are exactly are you asking for? The wordle squares to be replaced with directions? Aren't the squares very easy to understand. I love the squares tbh.
