### ISSUE TITLE
17 March Puzzle

### ISSUE THREAD

**Issue by GBflag** [teuteuf/worldle#121]
Today’s puzzle (17 March) is clearly Spitzbergen/Svalbard, an artic island territory belonging to Norway. The puzzle wouldn’t recognize this as an answer, nor would it recognize Norway since the outline clearly isn’t mainland Norway. Please be more attentive or change the parameters. Love the puzzle up to this point. Thanks.

**Comment by teuteuf** [comment]
I link this issue to this one to allow to accept both Spitzbergen & Svalbard: https://github.com/teuteuf/worldle/issues/46
