### ISSUE TITLE
Share URL in GroupMe shows React favicon

### ISSUE THREAD

**Issue by akump** [teuteuf/worldle#122]
![image](https://user-images.githubusercontent.com/22382028/159013507-306251cf-dd6d-423c-97c7-d02344bbf907.png)

**Comment by teuteuf** [comment]
Does it still happen?

The icon has been fixed a small time before you posted this issue, I wonder if it was some cache somewhere.

**Comment by akump** [comment]
@teuteuf yeah seems like iPhone's caching of the favicon is wack. I saw you had a PR weeks ago to address this, but it was still occurring for me. I did everything I could to clear the cache and it still was broken. I'll close the issue. Keep up the good word my dude.
