### ISSUE TITLE
Countries only

### ISSUE THREAD

**Issue by markdroka** [teuteuf/worldle#123]
I suggest making this a bit easier by having an option to use only countries.

**Comment by dylanismycat** [comment]
Yes, please no tiny islands, especially uninhabited islands. Perhaps an option to turn off small islands/territories

**Comment by Cargonat** [comment]
I came here specifically to request this. Maybe add an optional difficulty option to only use countries? And I know it can be vague what counts as a country, so maybe take something like the list of UN members?

**Comment by lineblom** [comment]
I agree and came here to suggest the same :) my reason is that I think the fun and learning outcome would be much higher without the high probability to get a tiny and often uninhabited island

**Comment by SueMeyers** [comment]
I agree with comments below.  The 'country' today (21 March) is an external territory of Australia.

**Comment by markdroka** [comment]
> I came here specifically to request this. Maybe add an optional difficulty option to only use countries? And I know it can be vague what counts as a country, so maybe take something like the list of UN members?

Well, they can always use Yakko's World!
[https://www.youtube.com/watch?v=IDtdQ8bTvRc&list=PLD5zm5BvnF-Gx0o5zZWON7RF4immtmrif&index=100]

**Comment by mechenginic0** [comment]
Agree with all of the above... It seems to be random islands and territories more often than not, rather than countries that are actually generally recognizable. Please remove the random tiny places that are not even inhabited, or provide an option to remove them!
Thank you for an otherwise fun game.

**Comment by oloverm** [comment]
I don't mind the tiny random ones, learn someting new every day. Also, what's random and obscure to you might not be for someone else.

A tip though: if you type "island", it's often one of the ones in the list that comes up.

**Comment by bsegafredo** [comment]
I've made this complaint/request before.  Based on the previous responses from the creator, it is not going to happen.  They are pretty adamant about it being this way.  They even went so much as to tell me to go create my own game that is limited to countries if that's what I wanted.  My only recommendation is to suck it up and play it how it is or stop playing, the creator is not open to suggestions.

**Comment by oloverm** [comment]
I saw the author said on twitter that they would limit small islands to max once a week, seems like a fair compromise.
________________________________

**Comment by SoulinaBowl** [comment]
This gets brought up repeatedly every time over of these guano rocks comes up, and despite overwhelming support, the creator's response is always "lol no" followed by closing the issue.

**Comment by bchivers-stanford** [comment]
ditto! countries only! or the option to turn off uninhabited islands!

someone please fork the repo and make this happen. I love Worldle but I these island days frustrate me so much

**Comment by teuteuf** [comment]
Some info about this:

https://twitter.com/teuteuf/status/1505249733434085392
https://twitter.com/teuteuf/status/1505624532085837827
https://twitter.com/teuteuf/status/1506037403848486918

To sum up: starting next friday, there will be a 7 days delay after a small island/country/territory is picked before it can pick another small island/country/territory.

**Comment by bsegafredo** [comment]
"A lot of people love those small islands".

...No as can be seen by this thread, that is not an accurate statement, But as I pointed out before the creator has little desire to listen to his players suggestions and has only implemented the change in hopes to get us to stop complaining on the forum...at least that's my hot take on it.

**Comment by teuteuf** [comment]
![Screenshot_20220322-000914.png](https://user-images.githubusercontent.com/3580153/159377769-24b74936-560b-4192-8c35-a906c6c9b0b0.png)

🤷

You can go play this variant here if it still doesn't fit what you'd like to play: https://countrydle.com

**Comment by bsegafredo** [comment]
What an immature response by trying to direct your players to a dead link. Well that's it. You've lost a player.  I get it you developed a game how you want it, but your absolute refusal to listen to the critiques of your game is frustrating to say the least.  You should have just ignored the criticism than respond with such childish responses that have no respect for players.  That is the end of the line for me.  This game has so much potential, but has been ruined by its creator's behavior.

**Comment by teuteuf** [comment]
👋
