### ISSUE TITLE
Multiple territories in 3/21/2022

### ISSUE THREAD

**Issue by Cakewalker872** [teuteuf/worldle#124]
Today's worldle features an image of two islands, one is the French territory, the other is McDonald's island. The image included then both, however only McDonald's island was correct, could the bigger island be removed from today's image?

**Comment by SueMeyers** [comment]
And these islands are not even a country, rather an Australian external territory that is barely visible on any map.  Can the game stick with independent countries please?

**Comment by Cakewalker872** [comment]
Worldle dosent have to be just countires. Countires are easy. If it was countires only I would never lose, I think the territories are fun and spice up everything

**Comment by Cakewalker872** [comment]
There are two separate islands there from my knowledge. The top is a French island, the other one which was the right awnser, is McDonald's island. Both islands are separate awnsers but are both in this image unless I'm mistaken. I've included the Google maps image below 
![Uploading Screenshot_20220323-135634_Maps.jpg…]()

**Comment by Cakewalker872** [comment]
Actually now that I look at it, it appears it was my mistake. There's more islands right there than I thought, the island which I'm looking at dosent seem to match the picture. I believe it was my mistake. Thank you!
