### ISSUE TITLE
Difficulty randomizer?

### ISSUE THREAD

**Issue by Thomas1873** [teuteuf/worldle#125]
I am full in support of Svarlbad, Christmas Island and the Heard Islands being included. But they need to be randomized out with other locations rather than clustered together.

**Comment by teuteuf** [comment]
Yep, I agree, it was pure random with no rules, just a bad coincidence they all have been picked in a row...
I introduced a cooldown delay of 7 days everytime one of this small island/territory/country, it should make things better! :)

**Comment by teuteuf** [comment]
(The new way to pick country/territory will start on next friday!)
