### ISSUE TITLE
Mobile rotated view distortion

### ISSUE THREAD

**Issue by Redpear149** [teuteuf/worldle#132]
On the Android mobile app, the rotated view sometimes distorts the image. Today, Mexico was compressed in the rotated view but fine in the regular view. But otherwise a great game!

**Comment by teuteuf** [comment]
Hello :)

Can you add a screenshot? I see nothing wrong on my side.

**Comment by Redpear149** [comment]
Unfortunately, I already played the game today, so all I see now is the image unrotated.  If it happens again I'll try that.

**Comment by Redpear149** [comment]
Actually, I was able to do it on the webpage and got this. 
![Screenshot 2022-03-24 163745](https://user-images.githubusercontent.com/102321810/160027149-1bef5935-11e9-4c1d-a2d6-86a1e59a2e43.png)
