### ISSUE TITLE
Wrong country/picture combination

### ISSUE THREAD

**Issue by agathevrignaud** [teuteuf/worldle#133]
The country shape / image used as a hint was one country (Sweden) and the game kept giving wrong directions (towards Ste Hélène in the Atlantic). See picture below : 

![SPOILER_unknown](https://user-images.githubusercontent.com/50956284/160100961-8586875f-17d5-41a4-9730-84784268d7dd.png)

A few friends and I have the same issue, some got Ste Hélène shape/directions and other a mix of both. No extra difficulty options activated.

**Comment by teuteuf** [comment]
Caused by app updated after guess has been input.

Should not happen anymore :)
