### ISSUE TITLE
Two different answers 25/03/2022 (Spoilers!)

### ISSUE THREAD

**Issue by tl1995** [teuteuf/worldle#135]
Hello,

Different people have had different answers to today’s Worldle. Some (such as myself) have had Saint Helena, and others have had Sweden (this led to a lot of confusion when discussing the difficulty of the answer with friends). From looking at the code and your responses to other issues I believe this may be to do with the small country cooldown timer that you have introduced. Some people keep the app constantly open on their phone, and it’s possible that for those people the app hasn’t updated and so they are still shown a small country that has been filtered out for those who have refreshed the app.

I’m not sure if there is an easy way to fix this, perhaps there is a way of notifying app users when a new feature has been introduced, or even forcing a refresh when one is introduced?

**Comment by AndoniLarz** [comment]
Can confirm I got this case too. I played between 00:00 and 01:00 and had to find Saint Helena while my colleagues who played later this day had to find Sweden.

When reopening the website to check, Sweden is displayed as the answer.

**Comment by ian2153** [comment]
I have seen this behaviour too on the Web interface, on an iPad Pro and an older iPad Air. On the iPad Air, both browsers had been open for days on end. Safari opened the URL and showed the same as all my other devices, but Chrome opened the alternate islands. So to summarise, same device, browsers been open for days, yet two different maps.

**Comment by mikevorys** [comment]
I was affected by the Saint Helena/Sweden issue as well.

SPOILER FOR 3/27/22 following this!!




Today I had Togo.  I'm playing on Google Chrome on my iPhone12.  My parents had French Southern and Antarctic Lands but they play via Chrome and Firefox on their PCs.  Would love to know what is causing these different answers.

**Comment by teuteuf** [comment]
Close all Worldle tabs and reopen it, it should update the app and display the same country everywhere.

Sometimes it needs to be done a couple of times to make it refresh.

**Comment by gavinpirrie** [comment]
Can confirm this fixed the issue for me!

> Close all Worldle tabs and reopen it, it should update the app and display the same country everywhere.
> 
> Sometimes it needs to be done a couple of times to make it refresh.

**Comment by mikevorys** [comment]
Awesome thanks!

Mike Vorys
(336) 995-6339
________________________________
