### ISSUE TITLE
Following Wordle model

### ISSUE THREAD

**Issue by 13AB5** [teuteuf/worldle#136]
I wonder if you would consider having a large set of guesses available but a smaller subset of possible answers like how Wordle is. I’m sure there are users that can guess extremely obscure islands but it’s more fun to actually be able to hone in on a country, and would be appealing to more people. At least define more clearly which kinds of countries/territories are allowed?

**Comment by chriscapitolo** [comment]
I second this suggestion. I know it's sticky territory to decide what should or should be included, but Sporcle manages to have only recognized countries in their quizzes without offending.

**Comment by acerock23** [comment]
No territories...please!
You're appealing to the minority of intelligent people 🤭
Thanks

**Comment by forrestedw** [comment]
I like having them there because I learn about them, but I always end up cheating on those days!
