### ISSUE TITLE
Allowing Duplicates

### ISSUE THREAD

**Issue by EswaramoorthyKarthikeyan** [teuteuf/worldle#137]
![Screenshot_20220326-021123_DuckDuckGo.jpg](https://user-images.githubusercontent.com/29886442/160198244-5e78becc-52fd-42c4-b34d-a0f2db7ab02b.jpg)

**Comment by nicovok** [comment]
my solution: #140

**Comment by kees** [comment]
I don't think this is fixed yet, but PR #140 should fix it...
