### ISSUE TITLE
Curiouser and curiouser.  Different country + unusual overlap.

### ISSUE THREAD

**Issue by cellmaker** [teuteuf/worldle#138]
Unlike others who do worldle with me, I got St. Helena (not Sweden) today, which I did not know.  Upon learning everyone else had Sweden, I reloaded the page and still got St. Helena.  Then upon a further reload I got Sweden with my answers for St. Helena.  Anyway, that's interesting!  See attached files:

![IMG_2255](https://user-images.githubusercontent.com/2539834/160202894-999e8257-bd77-4d38-b150-e51a986c69ac.png)

![IMG_2663](https://user-images.githubusercontent.com/2539834/160202926-3d6f88a8-25be-4038-90c1-986c2a02385e.png)
.

**Comment by throx** [comment]
A friend saw this yesterday. Today I actually got a different country after refreshing while it kept the same first answer. This led to some serious problems:
![Uploading 31B1145E-0544-44E8-8D7A-0A896BF0D8A8.png…]()

**Comment by jackieuk** [comment]
I had this exact issue yesterday and again today my country was different to that of my friends. Any idea how we can fix this? Refreshing is not changing anything.

**Comment by teuteuf** [comment]
Hello!

It's a cache issue, one of you still have the old code running and doesn't pick the Worldle with the small territories restriction.

If you are on PC, a force refresh should fix it, press Ctrl+F5.

On mobile, refresh isn't enough, you need to close all Worldle tabs and reopen it. You might need to do it a few time to make sure it refresh cache.

**Comment by jackieuk** [comment]
Thanks I’m going to try it now on mobile. 

Which user has the old code running? Example today I had Samoa but two of my friends had Vanuatu. Which cache is wrong? 

Thanks

**Comment by teuteuf** [comment]
This is your cache which needs to be refreshed. :)
