### ISSUE TITLE
Mismatch Between Map and Guess

### ISSUE THREAD

**Issue by briankeegan** [teuteuf/worldle#145]
Today:  went to site - saw photo of Togo.  Got it! 

 After, my partner told me that it wasn't correct!
When went back to site, i saw wrong image, but saying i got 100%.

<img width="767" alt="Screen Shot 2022-03-27 at 11 14 37 AM" src="https://user-images.githubusercontent.com/32174215/160288448-bad8b7da-a3cd-4804-bdad-453d50f5039b.png">

Possibly LocalStorage issue?

Heres what I copied from the output of `window.localStorage`

```
{
    "i18nextLng": "en-US",
    "hideImageMode": "{\"2022-03-13\":false,\"2022-03-27\":false}",
    "rotationMode": "{\"2022-03-13\":false,\"2022-03-27\":false}",
    "guesses": "{\"2022-03-13\":[{\"name\":\"BOSNIA AND HERZEGOVINA\",\"distance\":9554136,\"direction\":\"SW\"},{\"name\":\"BRAZIL\",\"distance\":0,\"direction\":\"N\"}],\"2022-03-27\":[{\"name\":\"SOUTH AFRICA\",\"distance\":4960062,\"direction\":\"NW\"},{\"name\":\"SENEGAL\",\"distance\":1789078,\"direction\":\"E\"},{\"name\":\"TOGO\",\"distance\":0,\"direction\":\"N\"}]}"
}
```

Love this app!!!  I haven't looked, but happy to help debug/right fix if you want any help.

**Comment by teuteuf** [comment]
You solved today's puzzle with previous version of the app, it has been updated after that.

So it displays what you should have seen today, but it displays also what you guessed today... So yes, it's a bit weird, but starting tomorrow, everything should work fine. :)

**Comment by briankeegan** [comment]
Wow! thanks for the quick feedback :)
