### ISSUE TITLE
FAQ page does not show answer to FAQ

### ISSUE THREAD

**Issue by c933103** [teuteuf/worldle#146]
Inside question mark section of the site, a section in it read: 

> Any question or suggestion?
> Check the [Worldle FAQ](https://worldle.notion.site/Worldle-b84ab0f002e34866980a4d47cf9291b7)!

Yet the linked site, https://worldle.notion.site/Worldle-b84ab0f002e34866980a4d47cf9291b7 , only shows some FAQ questions, and contain no answer to these FAQs.

Experienced the same on both Windows Firefox and Android Webkit-based browser

**Comment by MetalManiacMc** [comment]
![image](https://user-images.githubusercontent.com/93709189/160298002-ba2025da-7426-432c-866d-e3e370a78f62.png)
You know you need to press on the arrow right?
Anyway it works for me both on Chrome and Edge (W11)

**Comment by teuteuf** [comment]
Yep, you need to click on the arrow to get the answers.

I close this issue for now and if someone report this to me again, I'll try to explicit this.

**Comment by c933103** [comment]
Ah, didn’t know it is necessary to specifically click on the small triangle. The UI make me thought that I only need to click on the big title text to exapnd the question, which didn't work. Thanks for the response and the help.
