### ISSUE TITLE
Islands

### ISSUE THREAD

**Issue by msteen14** [teuteuf/worldle#149]
Please make the worldle countries only. The random islands are too confusing, and I can never get them right because they are so obscure. I am considering quitting playing the game because there are so many random islands included in the pool of options.

**Comment by gamesaucer** [comment]
It seems most people like them, but apparently someone did make a version that's just countries: https://www.countrydle.com/

I wonder if perhaps it would be a good idea to list this alternative somewhere that people can find it easily? Teuteuf seems to condone this alternate version so it might be helpful.

**Comment by davidsanger** [comment]
I find the islands some of the most interesting challenges and have been lucky enough to get some of them quite quickly. If they are recognized countries or territories then they are fair game and should be included.

**Comment by samosan21** [comment]
I respectfully disagree! These aren't random islands, these are all dependencies and territories, and the list is shorter than you'd think. Also they make for the most interesting challenges imo!

**Comment by teuteuf** [comment]
Already surveyed players and recently changed how country are picked to avoid too much small islands on a row.

Should be better for you! :)

I close this issue because I won't completely remove them from the game.
