### ISSUE TITLE
[Feature request] Practice Mode

### ISSUE THREAD

**Issue by Alligator023** [teuteuf/worldle#154]
An idea is to have the actual daily Worldle, and as a separate thing have a Worldle Practice Mode, where it chooses a random country (It probably shouldn't be allowed to choose the country that is the actual daily Worldle) and lets you practice against that country. Similar to [Ooodle](https://mathszone.co.uk/resources/grid/ooodle/)'s Practice Mode.

**Comment by RyuAzuku** [comment]
100% want something like this to be added! I want to play more than just one game a day.
