### ISSUE TITLE
Guadeloupe's coordinates wrong

### ISSUE THREAD

**Issue by LordPandamonium** [teuteuf/worldle#158]
The coordinates for Guadeloupe is no where near where the island (or any island) actually is. This will confuse players who use GP as one of their guesses and tries to measure from there. I imagine this will also cause an issue when GP is selected as the answer for the daily. 

`` {
    code: "GP",
    latitude: 16.995971,
    longitude: -62.067641,
    name: "Guadeloupe",
  },
``
![unknown](https://user-images.githubusercontent.com/27836571/161127630-b6d7af46-6610-407a-bc57-eaded65cd067.png)

This is more an issue with the google CSV that is used, but it is hardcoded in the source.

**Comment by teuteuf** [comment]
Fixed! Thanks for reporting it!
