### ISSUE TITLE
Enhancement request : Add wikivoyage link

### ISSUE THREAD

**Issue by emrxdev** [teuteuf/worldle#159]
Have been enjoying worldle for the last few days. And invariably I lookup wikivoyage pages every day for the country whose map is shown. Would be great if you can add a few links on the page such as wiki and wikivoyage for the right answer - would be best to show the links once the correct answer has been found or users run out of tries. 

Thanks for this nice game  and best wishes !

**Comment by TN73** [comment]
I came here to make this same request!  I look up the country or island every time.

**Comment by teuteuf** [comment]
Wikipedia link added! :)
