### ISSUE TITLE
Feature request - map my guesses

### ISSUE THREAD

**Issue by benevolent-boa** [teuteuf/worldle#161]
Hi, I'm loving the challenge of worldle each day. Would really like to see how bad my guesses were on the answer Google map at the end as well. I might even learn something that way too! Maybe a separate link to include the guesses, in addition to the current link that shows just the correct answer? Cheers!

**Comment by acerock23** [comment]
It would be great if the countries that have no access to the sea, ocean, etc. have a partial look at countries surrounding it.
My opinion
Thanks
