### ISSUE TITLE
Enhancement request: Change "truly random" to "truly random no-repeat"

### ISSUE THREAD

**Issue by rickbronson** [teuteuf/worldle#166]
Two of my kids and I love Worldle (although personally I'd change the name, it's a bit convoluted to say), thanks so much for providing it!  So, yeah, instead of having the "truly random" feature of choosing the country, I think it would be better to have it not repeat until you exhaust the list of countries.  This way you avoid the silly situation of having the same country appear two days in a row.  Do you really want a barrage of messages asking why you had the same country?

**Comment by tenormichaelk** [comment]
Didn't see Panama (earlier reference), haven't had this problem either!!!! Lots of interesting glitches here, we're still enjoying the game and learning geography!!!

**Comment by teuteuf** [comment]
https://twitter.com/teuteuf/status/1519214781701492737 :)
