### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by Kmqx4** [teuteuf/worldle#167]
Is there a way to show the scale somehow? Right now, a tiny area like the Isle of Mann, looks the same size as Brazil

**Comment by forrestedw** [comment]
I disagree. Having the Vatican and Russia on the same scale wouldn't work. And part of the fun for me is to determine from the shape which parts might be coastal.

**Comment by tehkate** [comment]
I think the option to add scale would be the compromise here just like you can take away pieces or randomly rotate the image.

**Comment by dtsch** [comment]
I agree with tehkate, a scale would be nice, especially if it was removeable in the difficulty options

**Comment by teuteuf** [comment]
I've added a a settings to replace proximity by size percent.

If the country you input is twice the size of the target: it will display 200%!
If the country you input is half the size of the target: it will display 50%...
