### ISSUE TITLE
Countries aren't the same

### ISSUE THREAD

**Issue by Bellsfolly** [teuteuf/worldle#169]
My husband and I play.  We have had different countries the last few days. He clicks the link I send him with my results.

**Comment by woctezuma** [comment]
Are you in different timezones? The puzzle is updated at midnight on your local device.

> A quelle heure est disponible le nouveau Worldle ?
>
>Le nouveau Worldle est disponible chaque nuit, à 0:00, heure locale de votre appareil !

Reference: https://worldle.notion.site/Worldle-4005ca16fc9341e7be8adcfd30628146

**Comment by woctezuma** [comment]
Another explanation: refresh the browser cache with `Ctrl+F5`.
- #162

**Comment by teuteuf** [comment]
Yep, it must be a cache issue, check this comment for details:
https://github.com/teuteuf/worldle/issues/162#issuecomment-1090659635
