### ISSUE TITLE
Image of country not showing on screen

### ISSUE THREAD

**Issue by are-g** [teuteuf/worldle#170]
It's happened once or twice in the past, but I cannot see the image of any country for today's identification.  How do I get an image to appear?

**Comment by woctezuma** [comment]
Did you enable the "hard mode" yesterday?

![Picture](https://i.imgur.com/MjN2Jru.png)

**Comment by teuteuf** [comment]
I made some changes on how images are loaded sometimes ago. I hope this fixed this kind of issue.
I close this ticket, let me know if you still have this problem.
