### ISSUE TITLE
Permission to translate?

### ISSUE THREAD

**Issue by gamesaucer** [teuteuf/worldle#172]
Hello! I would like to translate Worldle to Dutch, but before I do any work on that I want to ask whether that's OK first, since the README seemed to suggest that would be best. Besides that, there are a few things I want to mention as well that relate to translation:

- After looking in the code, it looks like territory names can't be translated at the moment. Are there plans to change this? If this is added I would be happy to also provide Dutch translations for them.
- There doesn't seem to be a way of selecting the language of the game at the moment. I assume it uses location data? If so, I would still like to ask that a way to change the language be added, in case that data is ever wrong or the person playing does not speak the local language well/prefers another language to the local one.

(P.S. I tried via Twitter before but got no answer, so I apologise for trying to contact you in two different ways)

**Comment by teuteuf** [comment]
Permission granted!

Sorry, I probably missed your message on twitter, I receive quite a lot of them, it's hard to keep up to date...

No problem to add translation, I would gladly merge a PR with new language! :)

I just made some changes for you to simplify country names translation, you can find a file named `countries.name.fr.ts`, you could do a similar one with translated country names in your language.
This function also need to be updated to pick the good translatation: https://github.com/teuteuf/worldle/blob/3b481adbf932c0be336ace2fca6df646d477dd5f/src/domain/countries.ts#L27
Please add the source of the country names translation on the file. :)

You're right, I need to add a settings to change the language...
Meanwhile, you can do it by adding a param in url, for instance, to use french translation, use this address: https://worldle.teuteuf.fr/?lng=fr

Let me know if you need help!

**Comment by malangali** [comment]
We have all of the country name data in all of the languages of the CLDR, with a selection mechanism. That is, if you choose French, you will get all the country names in French. If you choose Swahili, you will get all the country names in Swahili. We have this for somewhere between 200 and 300 languages. It would be pretty straightforward to mix our code into Worldle. Can we talk?
