### ISSUE TITLE
Add a link to Google maps

### ISSUE THREAD

**Issue by kenofthenorth** [teuteuf/worldle#173]
I think most users will visit Google maps on unknown countroes. It would be nice to have a link in the app that just went to a map. If the puzzle was already solved, a link to that country would be awesome. Also a link to Wikipedia for the country!

**Comment by woctezuma** [comment]
> Also a link to Wikipedia for the country!

There is. I think it was recently added.

> 👀 sur Google Maps
> 📚 sur Wikipedia

**Comment by teuteuf** [comment]
Yep, both links are already displayed after the end of a game.

If you use a dirty clone from the App Store or Google Play... Well, I can't update it and would highly recommend to avoid using it. :)
