### ISSUE TITLE
Today's country slightly tilted? (spoilers) 

### ISSUE THREAD

**Issue by Tetraodon** [teuteuf/worldle#178]
Was today's country slightly rotated? I have the 'randomly rotate country image' option unselected, but comparing it to Google maps (set to pointing north) it's at an angle. 
(Ignore my slightly rubbish attempts at today's 😬 geography has never been my forte but Worldle is helping me immensely in learning!) 

![Screenshot_20220415-122655_One UI Home](https://user-images.githubusercontent.com/39228863/163497390-d9d255d3-287b-45b5-ba75-a6db1901ab08.jpg)

**Comment by alexhou00** [comment]
Maybe it's because of the map projection. Google Maps uses the Mercator projection, which makes the south of the country larger. You can switch to Globe view on Google Maps and view from a specific angle, you will find that the country isn't tilted.

**Comment by Tetraodon** [comment]
Ah, thank you so much! I always forget how many different ways there are to project maps — that's awesome to know 😊
