### ISSUE TITLE
Keeps saying there is a new version

### ISSUE THREAD

**Issue by logiclrd** [teuteuf/worldle#180]
Every time I refresh the page, a banner tells me there is a "New Version" and to "Click to update". When tapped, this disappears but nothing else happens.

**Comment by miketotman-sd** [comment]
I also get this on Chrome 100 on Android 12

**Comment by ctfishman** [comment]
I get the same in Chrome on an iPhone. It did not happen in Safari, but I had never been to the site in that browser before going there just now to test. Fun game, thanks!

**Comment by teuteuf** [comment]
The notification should appear when I push some update on the game, it can be some minor things like small UI tweak or country name correction, so you might not see the difference, but it could have really updated something.

However, it seems there is issue for some people, the notification keep reappearing with no reason... I added a "Ignore" button on the notif to completely disable it.
