### ISSUE TITLE
Flagle, please!

### ISSUE THREAD

**Issue by da-viid** [teuteuf/worldle#185]
I would love to play a version in which the user can see the flag of the country instead of the outline. Ideally, I would like the ability to set the puzzle to display the map, flag or both.

**Comment by dtsch** [comment]
Seconded

**Comment by Ssnarf** [comment]
Something like this already exists. Not exactly as you requested but similar.
https://www.flagle.io/

**Comment by dtsch** [comment]
Nice find. Like you mentioned, not exactly as requested, but still quite good.

Would still be a dream to have it as an option in Worldle, or even at the very least have the flag show up once guessed correctly

**Comment by 9ps** [comment]
a better iteration of a "flag wordle game" is [this flaggle](https://ducc.pythonanywhere.com/flaggle/)

**Comment by bobpaul** [comment]
I think this is a duplicate of issue #42
