### ISSUE TITLE
Distance Between Bordering Countries?

### ISSUE THREAD

**Issue by anotheranotheruser** [teuteuf/worldle#190]
Why does a country bordering the target country show something other than 0 km? What is the measurement shown if not the closest distance between the two countries? Thrown by this today: SOUTH SUDAN 1,075km ⬅️ 94%

**Comment by woctezuma** [comment]
Distances are computed between country "centers".

**Comment by teuteuf** [comment]
Check the FAQ for more details about how distances are computed.

But yes, as @woctezuma answered, it's a center to center distance.
