### ISSUE TITLE
same answer recently

### ISSUE THREAD

**Issue by wiporwil** [teuteuf/worldle#191]
(spoiler for today) monaco was the answer maybe two weeks ago. i remember because i got it wrong and looked it up and read all about it, and this time got it on the first try. i'm sure answers will begin to repeat at some time, but why so close together?

**Comment by woctezuma** [comment]
It is random.

**Comment by Mercator1569** [comment]
As with Monaco, today's map silhouette map has been shown before - what's happening?

**Comment by woctezuma** [comment]
It is in the FAQ: it is random.

**Comment by Mercator1569** [comment]
A third country that has been shown before has just appeared, and just a day after the second country to do so. If it happens twice, it might be random, but three times looks like a glitch.

**Comment by leahsharzer** [comment]
Hi all, I have the same issue - third day in a row of a country that has already been a recent answer - if this is random, that's crazy, I think it's worth at least checking for a glitch! First was Monaco, then Uruguay and then today (spoiler alert) Costa Rica.

**Comment by teuteuf** [comment]
https://twitter.com/teuteuf/status/1519214781701492737 :)
