### ISSUE TITLE
Suggestion List - Sort and View

### ISSUE THREAD

**Issue by TimothyJCowen** [teuteuf/worldle#195]
Currently when the user starts typing in the suggestion box, they are given a list of options that fit with whatever they have typed. It looks like this:
![image](https://user-images.githubusercontent.com/32042011/165511983-2aa66d74-f97d-4407-b121-61047e4f43df.png)

The order of the items in this list doesn't always make sense. As you can see in the image, it is not in "proper" alphabetical order. For the _most_ part it is, but there are many, many instances of countries being _a bit_ out of place, or sometimes a lot. I would love to see the list be sorted before being presented to the user.

In addition, it would be great if the list could pop up as soon as the user focuses on the suggestion box. Sometimes I am looking for just a list of the possible options to see if any stand out to me, and I resort to typing random letters. If I could see all of them at once in a nice, sorted list, that would be ideal.

**Comment by woctezuma** [comment]
I don't think the goal was to show the list in alphabetical order. I imagine the list is sorted by similarly to your text input.

**Comment by teuteuf** [comment]
improved suggestions: alphabetical order, list all when no text input, bold on highlighted suggestion, auto select first suggestion on enter
