### ISSUE TITLE
Different challenges today?

### ISSUE THREAD

**Issue by OpenRobert55** [teuteuf/worldle#198]
Today (1 May) my challenge was different than the one my two sons had. I will not spoil the today challenge by revealing both challenges, but both started with a C and were in the same region of the world. A bug?

UPDATE. Sorry, I just noticed this issue has been reported and solved already.

**Comment by PromptServiceNZ** [comment]
Kia ora,
Where was it reported and solved please? Can only see your update but I still got a different clue to my partner. Checking if I need to do anything before tomorrow. 
thanks.

**Comment by OpenRobert55** [comment]
Here is the link to the issue where the solution for this behaviour can be found: https://github.com/teuteuf/worldle/issues/162#issuecomment-1090659635

**Comment by PromptServiceNZ** [comment]
Hmmm, I'm not sure that's it as we all had the latest version of the app.
