### ISSUE TITLE
Canary Islands should be a separate card

### ISSUE THREAD

**Issue by ScriBanana** [teuteuf/worldle#201]
Hey,

We were thinking about dd6477eb559ca2bc69c8941c42f5bca3171ef125 with some friends and were wondering why The Canary Islands where added on the Spain card. Many an island like that are considered "territories", regardless of their administrative link to their country's mainland; The South Sandwich, Reunion Island, Bouvet Island, etc. So having the Canary as a separate card makes sense and adds game content.

What do you think?

**Comment by teuteuf** [comment]
As mentioned in the FAQ, I use the ISO 3166-1 standard as country list.
The Canary Islands aren't in there, that's why it's not a independent entry in the game.
And that's why I updated the Spain image to include the Canary Islands. :)
