### ISSUE TITLE
Suggestion - Show a league table of recognisability based on correct guesses

### ISSUE THREAD

**Issue by tim1882** [teuteuf/worldle#229]
Show a league table of the recognisability of the countries based on the mean score of all correct guesses (maybe have a value 10 for six incorrect guesses?).  The lower the score the higher the rank.

And/or show a ranking based on the total proportion that were correctly guessed at all.

I think todays (2nd June) would be top! (so far).

**Comment by teuteuf** [comment]
All data are stored locally on your device, I don't have these data on my side, so not possible.

There is around 2M players every day, so won't be able to change this easily and without a big charge, so I close this issue.
