### ISSUE TITLE
Make it more educational 

### ISSUE THREAD

**Issue by Alkreitner** [teuteuf/worldle#231]
It would make for a more educational exercise if at the end of 6 incorrect guesses, not only is the correct answer given, but a map would also be provided to help in placing the country’s location. 
i now have a rough idea where Bulgaria is but to see a map of it in relation to the other countries in the region that I may know better would be beneficial.

**Comment by teuteuf** [comment]
Hi!

There is already a link to google maps when you succeed (or fail) to guess the country.
Have you seen it?

I close this issue, let me know if the link is not displayed on your side.
