### ISSUE TITLE
What does 'Streak' mean?

### ISSUE THREAD

**Issue by amcolemanacz** [teuteuf/worldle#245]
And how is it computed?

**Comment by jackgreenburg** [comment]
Your "streak" is the number of days in a row where you guessed the correct country.

It is computed by saving all your guesses in local storage ([saved in this file](https://github.com/teuteuf/worldle/blob/7e52479f603f008f159a172ef26b97623d8ee51a/src/domain/guess.ts#L14)), and then iterating over them ([calculated in this file](https://github.com/teuteuf/worldle/blob/7e52479f603f008f159a172ef26b97623d8ee51a/src/domain/stats.ts#L13)).
