### ISSUE TITLE
Cayman Islands shape incorrect 

### ISSUE THREAD

**Issue by Ear3FL** [teuteuf/worldle#247]
The Cayman Islands consist of three islands but the game only shows one - Grand Cayman - rather than all three.

**Comment by hmtpsych** [comment]
Yes, this isn't this first time recently that this has happened with island nations/territories. A month or so ago, the game would show all land masses associated with the answer, but that seems to have stopped and it makes this game more frustrating than fun.

**Comment by gilesNow** [comment]
I LIKED it the initial version, minus the 2 mico islands such a lonnnng ways off

in fact i greatly preferred that...  makes it more challenging to not be able to instantly tell that it's an island, or part of a larger landmass

**Comment by Ear3FL** [comment]
@gilesNow 
It’s misleading and inaccurate. If I’m guessing a nation based solely on the shape then all the major land masses should be included. If we’re guessing individual islands rather than nations, that would be a different game, and the correct answer would be Grand Cayman. (For the United States, I believe Hawaii was included, as it should be, even though it is quite far from the mainland.)

**Comment by gilesNow** [comment]
so serious. 
well, i won't argue the point with you..   though those two tiny islands (which ARE so far away) would hardly be included with say the hawaiian chain

misleading & inaccurate? 🙀😸
 we'll just have to disagree
