### ISSUE TITLE
OpenStreetMap instead of Google Map [GAFAM]

### ISSUE THREAD

**Issue by timalmoon** [teuteuf/worldle#25]
Hi,

Congratulation for your code.
But, i think it's more proper with a leaflet of OpenStreetMap.
No Google or Gafam tracking with use of this service.

https://wiki.openstreetmap.org/wiki/Leaflet

Thanks in advance.

**Comment by winniehell** [comment]
@teuteuf what do you think of having links to both?

**Comment by winniehell** [comment]
see also https://github.com/teuteuf/worldle/pull/66#issuecomment-1066134006
