### ISSUE TITLE
Result Graphic For Sharing

### ISSUE THREAD

**Issue by Aroontheprune** [teuteuf/worldle#250]
Thanks for this game, loving it
Part of the fun is sharing results with friends & family
I know youve been inspired by Wordle
But the shared graphic is similar (green & yellow) boxes that it's immediately obvious if we are comparing Wordle or WorLdle. Maybe make most of the boxes Blue, and the 10% box green?
Then when comparing with friends we can see easily which game we are comparing?
Oh and put a capital L into worLdle to make it easier to read the difference?
Thanks so much for creating this fun & educational game
Au Revoir
Arun, Scotland

**Comment by teuteuf** [comment]
Hey! :)

Thanks for your suggestions, but I prefer to keep it like this, I like to keep it this way as an homage to the original wordle and people are used to see the result like this.

**Comment by Aroontheprune** [comment]
Nice to hear from you
Thanks so much for the game, it's very cool
Sending you screenshot to see how it looks when comparing with friends
Go on, try Blue! 😆
