### ISSUE TITLE
Site not rendering properly

### ISSUE THREAD

**Issue by govisi** [teuteuf/worldle#251]
Hi,

Checked in both Chrome and Firefox desktop, empty screen shown. Could you pls check?

**Comment by LHGaravello** [comment]
Same here, it works on Microsoft Edge

Chrome:
![image](https://user-images.githubusercontent.com/107927814/174790332-d05ba6bc-2191-4e9f-9127-54430c6b534b.png)

Source code on Chrome:
![image](https://user-images.githubusercontent.com/107927814/174790548-d36f9055-5a56-4880-a10f-b9f025508724.png)

Edge
![image](https://user-images.githubusercontent.com/107927814/174790443-3dd3fc65-eee2-4187-8c87-4f2cf877b4d9.png)

Source code on Edge:
![image](https://user-images.githubusercontent.com/107927814/174790630-4d91f97a-cb66-4205-b634-2e35157c702e.png)

**Comment by teuteuf** [comment]
It seems there was an issue with the service I use for hosting.

https://t.co/Hb7lRJ2ND6

It's probably related to this.

Let me know if it's still happening.
