### ISSUE TITLE
Feature request: where is the Antarctic Peninsula? I am lost and tired!

### ISSUE THREAD

**Issue by HomelessPenguin** [teuteuf/worldle#255]
Outline of Antarctica appears to be sourced from Edgar Allan Poe and not an atlas. Unless something has happened to the Antarctic Peninsula? I'm lost!

**Comment by teuteuf** [comment]
🗺🔨🐧

🙏

**Comment by HomelessPenguin** [comment]
Much better. I'd recognise that instantly, rather than the complete fail I had today. Penguin happiness! Thank you!
