### ISSUE TITLE
USStatesle ?

### ISSUE THREAD

**Issue by DavidLloydOwen** [teuteuf/worldle#275]
I look forward to my daily Worldle - consumed with my morning coffee!
And I'm learning a lot about world geography as a result.
(The link to Google Maps is a great idea.)
How about a similar game based on US States? ...or French départements?

**Comment by teuteuf** [comment]
Someone already made a version with the US states:
https://outflux.net/statele/

I haven't planned to make a version with French department, but if someone want to do it, feel free to use Worldle code ! :)

**Comment by DavidLloydOwen** [comment]
Hi teuteuf. On the Statele website it says to raise Statele suggestions here in your Worlde issue repository. Are you OK with that?
