### ISSUE TITLE
Emovi suggestion

### ISSUE THREAD

**Issue by DavidLloydOwen** [teuteuf/worldle#279]
Hi teuteuf
(Sorry if this is the wrong place to register an Emovi issue.)
Suggestion: Allow the player to propose their own selection of a movie title (possibly with an IMDB citation) in the "Create your own Emovi!" section...?

**Comment by nicovok** [comment]
i think you should share you issue there: [teuteuf/emovi](https://github.com/teuteuf/emovi/issues)

**Comment by DavidLloydOwen** [comment]
Thanks, nicovok.

**Comment by DavidLloydOwen** [comment]
Issue created in teuteuf/emovi

**Comment by DavidLloydOwen** [comment]
nicovok: do you know of a repository for leaderboardle issues, by any chance?
