### ISSUE TITLE
Different countries are displayed between loading and refreshing

### ISSUE THREAD

**Issue by nsimonovici** [teuteuf/worldle#286]
Hi there,

Thanks for all the good work around this great game =) there is nothing to comment the game is perfect as it is but I encountered a small glitch. 

Today I noticed for the N-th time a strange behavior.

I first loaded the game tab on my phone's (Huawei p20) Mozilla, displaying Dominican Republic.

Hence I enter the answer, bullseye.

Now I'm sensing something fishy because Dominican republic has been the daily country a few days ago (even if I did not play this day).

I hit refresh, now another country appears instead of the island, but my first and winning guess remains, preventing any new attempt for the second country today =)

I wanted to highlight this phenomenon.

Cheers
![Screenshot_20220721_123158_org mozilla firefox](https://user-images.githubusercontent.com/44460830/180195629-241e9ed5-ed69-4ff7-936a-2e990ae81b9c.jpg)
![Screenshot_20220721_123209_org mozilla firefox](https://user-images.githubusercontent.com/44460830/180195637-ed1d4374-73cd-427c-851a-b73f0705d57b.jpg)
![Screenshot_20220721_123344_org mozilla firefox](https://user-images.githubusercontent.com/44460830/180195640-b099fc72-a57c-4a38-a8de-ec9cebcb6142.jpg)

**Comment by kkinva** [comment]
I have a similar issue. For me, today’s answer is Malawi. It took 4 guesses. Then something happened and the map changed, but the guesses are still there indicating it’s Malawi. But it’s not. I love this game!!
