### ISSUE TITLE
Lithuania: missing stretch of land from Klaipeda to Nida

### ISSUE THREAD

**Issue by stefanvds1** [teuteuf/worldle#293]
https://www.google.com.sg/maps/place/Lithuania/@55.509404,20.7562634,9z/data=!4m5!3m4!1s0x46dd94140f33be13:0xf30a54d3a55dbab9!8m2!3d55.169438!4d23.881275

**Comment by DavidLloydOwen** [comment]
Hi Stefan. A gentle suggestion: Don't put the current solution in the title of an issue and suffix it "(spoiler alert)".

**Comment by teuteuf** [comment]
Fixed! Thanks!
