### ISSUE TITLE
Map of Macau is missing ⅔ of its territory

### ISSUE THREAD

**Issue by BOhUiginn** [teuteuf/worldle#297]
The silhouette of Macau is missing about ⅔ of its territory.

Correct territory:
![FF7F297A-249E-49A5-B73F-9C5B05576BDC](https://user-images.githubusercontent.com/2617501/183462742-2d9831c3-a63f-4340-8b4c-02727e6b236c.jpeg)

Currently shown:
![5FA611CF-6718-44C0-971C-5E72136A933F](https://user-images.githubusercontent.com/2617501/183462884-f622f050-b955-402c-98ff-fd8e8526aefa.jpeg)

**Comment by teuteuf** [comment]
I think this is a screenshot of a unofficial clone of Worldle, I recommend you to use the only official version available here: https://worldle.teuteuf.fr. The image has been fixed there to include the whole territory.
