### ISSUE TITLE
I keep getting the same countries

### ISSUE THREAD

**Issue by googleediting** [teuteuf/worldle#298]
I feel like there's an uneven distribution of countries.

I have gotten eswatini 3-4x out of maybe 30 games today.
I think that I frequently get Saudi Arabia, Argentina, Sri Lanka, South Africa, Iraq, Iceland, UK. Albania, Serbia, etc
There are a ton of countries which I have never gotten.
I've played probably 75-150 rounds.

I really wish I could cycle through all >193. It'd probably be perfect to limit a country to repeat 2-4x in 1 cycle of all >193.

Additionally, I would like 3 options: 1) Only 193 (or whatever) countries. 2) Only the others (overseas territories, or whatever you'd like to call non-UN-recognized places). 3) Both 193 + all the others.

**Comment by FburgStokeFan** [comment]
One could simply just shuffle the countries and then load them in a queue.  Then, when the queue is empty, start the process over, so every 193 days a new cycle.  This would at least remove "close" three-peats between cycles, but still guarantee all countries per cycle.  I haven't read the source code so don't know how countries are managed.

**Comment by NickSto** [comment]
@FburgStokeFan I like the shuffle idea, though it would mean that theoretically when you're toward the end of the cycle you'd be able to narrow down the guesses by what's left. Realistically I guess few people would be able to do this from memory, but if your house rules allow looking at the list of previous answers you could figure out what hasn't been used yet. Either way, you could easily mitigate this by making the cycle like 160 days and just drop the last 33 countries in the shuffle.

**Comment by teuteuf** [comment]
There is a rule in the picking algorithm to avoid too many repeats: a country can't be picked if it's already been selected in the last 100 days.
It allows us to continue the game to run indefinitely, to keep some repeats to make sure we remember what we could have learned on a previous day, and to avoid being predictive of the possibility of the picked for the next day if we play for a long time.
