### ISSUE TITLE
16 August solution

### ISSUE THREAD

**Issue by Crube666** [teuteuf/worldle#302]
Is Guernsey, but the map included Alderney and Sark, which are separate territories...

**Comment by DavidLloydOwen** [comment]
The Bailiwick of Guernsey (the correct name for the Crown Dependency which includes the island of Guernsey) also includes the islands of Alderney and Sark. (There are 3 Crown Dependencies: the other 2 are the Bailiwick of Jersey and the Isle of Man.)
