### ISSUE TITLE
Yemen map

### ISSUE THREAD

**Issue by dgndenver** [teuteuf/worldle#304]
A few sites use the map of Yemen you use for the outline of it, with straight lines and sharp angles on the north. But the great majority use a very different one. See https://www.google.com/search?client=opera&q=yemen+map. The sites with the more curved and irregular shape include Google Maps, the Encyclopedia Britannica, and the CIA World Factbook. I tried to find an official site for the government of Yemen but have been unable to find one.

**Comment by teuteuf** [comment]
Fixed! Thanks!
