### ISSUE TITLE
20 August solution 

### ISSUE THREAD

**Issue by DavidLloydOwen** [teuteuf/worldle#305]
The map of the Yemeni Republic is missing the island of Socotra.

**Comment by teuteuf** [comment]
Fixed! Thanks!

**Comment by DavidLloydOwen** [comment]
Thanks, teuteuf. The absence of the island meant one didn't realize that the southern border was most likely a coastal border which would have helped situate the country.

**Comment by DavidLloydOwen** [comment]
https://github.com/teuteuf/worldle/issues/299#issuecomment-1212726110
If that is indeed the case, teuteuf, how did you fix it?
(As always, many thanks for a fantastic game.)
