### ISSUE TITLE
Channel Islands & Isle of Man

### ISSUE THREAD

**Issue by Arb0l** [teuteuf/worldle#307]
These aren't countries. They're a dependency of the UK.

**Comment by DavidLloydOwen** [comment]
Check author teuteuf's definition of the game in "?": "Each guess must be a valid country, territory, ..." Game isn't restricted to countries.

**Comment by Arb0l** [comment]
Thanks David, that’s true, but still rather too arbitrary! Geography geeks are sticklers for reliable definitions.
________________________________

**Comment by DavidLloydOwen** [comment]
🙂
