### ISSUE TITLE
Rwanda

### ISSUE THREAD

**Issue by BOhUiginn** [teuteuf/worldle#308]
The outline is WAY too linear. For a country that has absolutely no straight borderlines, this shape has too much straightness. Is there a way to update that?

**Comment by teuteuf** [comment]
Do you use the web version available on https://worldle.teuteuf.fr? Rwanda hasn't been picked recently so you should not have seen it. If you use an unofficial app or other website, it's probably not updated with my corrections, I recommend you to use the web version with the link I put before.

**Comment by BOhUiginn** [comment]
I use the site and the app in the Apple App Store (screenshot attached). Is that app not you?![image](https://user-images.githubusercontent.com/2617501/187321910-409495f2-63ec-4065-9867-353fed334f0c.png)
