### ISSUE TITLE
Islas malvinas (falkland islands)

### ISSUE THREAD

**Issue by Panchito98** [teuteuf/worldle#309]
The Islas Malvinas ( falkland islands ) are currently a territory in dispute. There is a diplomatic conflict between Argentina and great britain about this and it is  delicate subject especially for the argentinian people who still claim thet they belong to the southamerican country because they were invaded by the british governmet.

**Comment by ge-source** [comment]
The Falkland Islands are not “a territory in dispute”.
They are British. Full stop.
Many British troops died preventing a hostile invasion in the early 1980’s.

**Comment by qwertyuf29** [comment]
Regardless of whether it’s part of Argentina or the uk, it is not an independent country. It Should not be listed as in the country list for this game. Suggest you remove it.

**Comment by DavidLloydOwen** [comment]
https://github.com/teuteuf/worldle/issues/307#issuecomment-1221911988

**Comment by teuteuf** [comment]
The ISO 3166-1 standard is use as source for the list of possible answers. I'll let you check it to see what can be picked according to this standard.
