### ISSUE TITLE
Archives

### ISSUE THREAD

**Issue by jrottenberg** [teuteuf/worldle#31]
Hello !

Great variant, thank you !

I've missed the past few days, is there a way to get a link to the past games ? ie without changing the clock on my computer.

**Comment by teuteuf** [comment]
It's not possible directly in the game but you can use the way back machine from Internet Archive :
https://web.archive.org/web/*/https://worldle.teuteuf.fr/
:)

**Comment by jrottenberg** [comment]
Ah yeah good point, I hope they will crawl daily now that it's getting popular.
