### ISSUE TITLE
Canada does not look like Canada 

### ISSUE THREAD

**Issue by jenad81** [teuteuf/worldle#312]
I would say the proportions are off, but everything looks tilted as well. Tilted and squished. 

![A429A2A4-EF19-4B78-B16E-A77AA5077DAD](https://user-images.githubusercontent.com/112568721/187714359-271201e0-ca96-4743-b68b-3f588de96ef2.jpeg)

**Comment by armandocolpa** [comment]
It might be due to the projection the game uses? As you know, most maps that we see use the Mercator projection. This keeps the proportions and location correct (for sailing) but the size is way off. Maybe the game is using a different projection?
