### ISSUE TITLE
Show distance and direction in share

### ISSUE THREAD

**Issue by Superty** [teuteuf/worldle#32]
I think the current thing that gets copied when sharing isn't that great. I think showing the distance and direction would be much better, i.e. showing the information you got from each guess, just like wordle. Something like

#Worldle 19 X/6
4412km ↘️
4422km ↙️
2685km ⬇️
1596km ↘️
938km ⬅️
676km ⬆️

**Comment by Superty** [comment]
Hmm okay! Personally I would still suggest at least adding the arrows to the current share, but an option would be great too. :)

**Comment by Superty** [comment]
By the way, thanks for making this, it's a really fun game!

**Comment by eminphi** [comment]
Here's a design idea. Not too explicit but includes directions.

#Worldle #23 5/6
🟩🟩⬛⬛⬛ ↘️
🟩🟩🟩🟨⬛ ⬆️
🟩🟩🟩🟩⬛ ↘️
🟩🟩🟩🟩⬛ ↙️
🟩🟩🟩🟩🟩

**Comment by Superty** [comment]
And you can put a 🎉 in the final column of the winning row!

**Comment by Superty** [comment]
I guess for me the most common outcome is that I don't get the answer, and I want to compare my closest distance with my friends. And I can't tell the difference between 93% and 98% with my friends. Maybe when you lose, add an extra element at the top indicating the best distance?

#Wordle #26 X/6 98%

**Comment by teuteuf** [comment]
> Here's a design idea. Not too explicit but includes directions.
> 
> #Worldle #23 5/6 🟩🟩⬛⬛⬛ ↘️ 🟩🟩🟩🟨⬛ ⬆️ 🟩🟩🟩🟩⬛ ↘️ 🟩🟩🟩🟩⬛ ↙️ 🟩🟩🟩🟩🟩

Yes

**Comment by teuteuf** [comment]
Yeah, I like these suggestions! :) Better than displaying explicitly the km, but a bit more explicit! Thanks!

**Comment by teuteuf** [comment]
Done! :)

Thank you for your suggestions!

#Worldle #28 2/6 (100%)
🟩🟩🟩⬜⬜↙️
🟩🟩🟩🟩🟩🎉
https://worldle.teuteuf.fr

**Comment by eminphi** [comment]
Awesome! Thank you.
