### ISSUE TITLE
Bonus round doesn't work with translations

### ISSUE THREAD

**Issue by Vengirni** [teuteuf/worldle#332]
Normally, I have Worldle set to Polish, and the regular mode worked fine to me thus fine. However, it seems like the game has added bonus rounds, and something was bugged. It asked me to type the neighboring countries of Norway, but my answers were rejected. Only after the third rejected answer, I switched the game to English and only then it accepted my answers as it should.
![obraz](https://user-images.githubusercontent.com/86624845/195988414-949e1bc4-6436-4a4e-b2bc-ef2e4062f8e6.png)

**Comment by ghuotvez** [comment]
Same for me, french answers even though being the right one, gave me errors.

**Comment by Kiwettz** [comment]
Unfortunately same problem here in French 😔
But idea's great!

**Comment by webfil** [comment]
To be merged with request 333

**Comment by teuteuf** [comment]
We are working on a fix on this and other issues with bonus rounds. We'll keep you updated as soon as it's fixed!

**Comment by paferrat** [comment]
Looking forward to the fix. I love this game :-)

**Comment by Lekgolo** [comment]
![image](https://user-images.githubusercontent.com/30934659/196447235-6c73e9f0-4167-41ea-a171-bf6549fb6c31.png)

Yep got the same

**Comment by teuteuf** [comment]
Fix has been deployed! Everything should run smoothly now. :)

**Comment by Patriccollu** [comment]
@teuteuf Where can we find the translations for the Bonus round?
