### ISSUE TITLE
All t("xxx") in the code are invalid

### ISSUE THREAD

**Issue by yuannancheng** [teuteuf/worldle#43]
All t("xxx") in the code are invalid

**Comment by teuteuf** [comment]
You gonna have to give me more details, I don't understand why they would be invalid.

**Comment by yuannancheng** [comment]
I'm sorry.

For example [/src/components/panels/Settings.tsx#L22](https://github.com/teuteuf/worldle/blob/67db30bdf79c0965c19acd53f5744c1773eb307d/src/components/panels/Settings.tsx#L22), the title of the settings page should It is `Settings`, but it is not. Like this screenshot, the variables defined in `/src/i18n.ts` are not actually used.

I tried using `console.log(language)` in [getCountryName function](https://github.com/teuteuf/worldle/blob/67db30bdf79c0965c19acd53f5744c1773eb307d/src/domain/countries.ts#L1135) and I got `undefined`

And:
My browser language is Simplified Chinese
My browser is Chrome 98.0.4758.82

![20220217162653](https://user-images.githubusercontent.com/52841727/154435590-83192d72-6f88-4c62-b5a4-68332a244a5e.png)

**Comment by teuteuf** [comment]
Okay, thanks for reporting! I'll investigate that!

**Comment by teuteuf** [comment]
Hey! I've seen you closed the issue, I recently added english as default language, did it fix your problem?

**Comment by yuannancheng** [comment]
Yeah, it fixed my problem, so I closed the issue. Thank you. @teuteuf
