### ISSUE TITLE
Directions are sometimes off

### ISSUE THREAD

**Issue by friedrich** [teuteuf/worldle#51]
The direction arrow sometimes points diagonally even if a horizontal or vertical direction would be much more appropriate.

For example: Sweden is considered to be NE of Algeria, while the bearing is just 15 degrees, which corresponds to N.

<img width="544" alt="Screenshot 2022-02-21 at 22 03 04" src="https://user-images.githubusercontent.com/107749/155026268-c499569c-7937-41bd-90de-bd9cdca1422a.png">

**Comment by teuteuf** [comment]
Thank you @friedrich for reporting it and for your solution suggestion! :)
