### ISSUE TITLE
[Bug] The graphic used for Rwanda is incorrect

### ISSUE THREAD

**Issue by topher-skinner** [teuteuf/worldle#68]
Currently, the graphic used for Rwanda is a duplicate of the graphic used for Saudi Arabia.

![incorrect country mapping](https://user-images.githubusercontent.com/89873783/156680919-9ff8c139-4dba-40db-8f50-66437423c2d7.jpeg)
![rwanda actual](https://user-images.githubusercontent.com/89873783/156680923-7a151f08-f90f-46ae-a552-9a5d562f4c6e.jpeg)
![saudi arabia actual](https://user-images.githubusercontent.com/89873783/156680925-217c90a4-9382-48b1-baed-2d2971e61880.jpeg)
![rw-vector](https://user-images.githubusercontent.com/89873783/156687199-cea42488-0042-4348-934e-3ffbe9b37516.svg)

.

**Comment by teuteuf** [comment]
Already reported here: https://github.com/teuteuf/worldle/issues/29
I'm curious, how did you get Rwanda? Changed date ? Forced a specific country?

**Comment by topher-skinner** [comment]
I cloned the repo about a week ago to make a couple of changes. One of my users found the issue, but I noticed that it would affect this repo as well. I missed the earlier report of it when I checked, my apologies. Would be happy to submit a PR and/or help with #29 if you'd like.
