### ISSUE TITLE
Country Outline Worldle

### ISSUE THREAD

**Issue by Louie1andonly** [teuteuf/worldle#71]
Today's, 03/04/22, "country" 😡 outline is wrong according to Google Maps! Unless the COUNTRY has lost landmass to the ocean!?!?

**Comment by guidecayeux** [comment]
I would say that the landmass is quite accurate. 

https://worldle.teuteuf.fr/images/countries/io/vector.svg

![image](https://user-images.githubusercontent.com/37122136/156795255-92990fb9-522a-4097-ac62-10889c2a88fb.png)

Am I missing something ?
