### ISSUE TITLE
feature request: a sense of scale

### ISSUE THREAD

**Issue by ibarland** [teuteuf/worldle#75]
It'd be nice to allow including a sense of scale -- either an image of one of a few reference-countries, or even just stating the country's area in text.  This could be a preference by itself, or bundled with other future features as part of an "easy mode".

(Granted, it's not as pure a puzzle that way, but for myself I think it'd enhance enjoyment -- a country's relative size is definitely part of how I my brain interprets the country's shape/boarders.)

**Comment by teuteuf** [comment]
Hello! Thanks for your suggestion!
It's already on my list, here is the corresponding issue: https://github.com/teuteuf/worldle/issues/9
I close this one to avoid duplicates :)
