### ISSUE TITLE
Proximity percent should be floored instead of rounded

### ISSUE THREAD

**Issue by teuteuf** [teuteuf/worldle#78]

**Comment by auxesis** [comment]
Current rounding behaviour looks like this:

![image](https://user-images.githubusercontent.com/12306/157853327-dcbac05f-a62d-45b7-aac8-2950f82de22f.jpeg)

**Comment by teuteuf** [comment]
Fixed! :)

**Comment by auxesis** [comment]
Thank you @teuteuf!
