### ISSUE TITLE
Nonexistent country

### ISSUE THREAD

**Issue by squidwardstikiland** [teuteuf/worldle#79]
israel should not have been the correct answer to todays worldle. Considering they are illegally occupying Palestine and violating their basic human rights.  The correct answer should be Palestine, israel does not exist!

**Comment by randomguy213** [comment]
Would you like to point to me where Palestine is on any map?

**Comment by randomguy213** [comment]
No, I'm pretty sure you're wrong. Palestine is not a country so therefore it would be impossible for Israel to illegally occupy it since it is their own land. Israel does exist you saying that it does not is just pure Anti-Semitism.
