### ISSUE TITLE
Subdivisions second round

### ISSUE THREAD

**Issue by The-Linguist-LL** [teuteuf/worldle#80]
After we guess the country, we should have a choice to guess a 1st level subdivision of the country. This game is great, but very short.

**Comment by teuteuf** [comment]
Thanks for your suggestion!

I think I'll keep it to one thing to guess a day to keep it simple!
But if you want more geographical challenge, you can check some site like [Sporcle](https://www.sporcle.com/) after your daily Worldle, it can be a good way to practice! :)
