### ISSUE TITLE
Inaccurate map of Israel

### ISSUE THREAD

**Issue by Yaron-Ha** [teuteuf/worldle#82]
The map shown in https://github.com/teuteuf/worldle/blob/main/public/images/countries/il/vector.svg is incorrect.
It doesn't include the Golan Heights whom Israel have annexed, nor does the West Bank which is occupied by Israel (and usually shaded with stripes or a special color to indicate controversial territories).
Instead it seems you just omitted the Golan and the WB completely...

Here is a map from the Hebrew Wikipedia, which more accurately portrays the borders of Israel.
https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Israel_Map_by_The_Legal_Status_of_The_Territories-6.svg/800px-Israel_Map_by_The_Legal_Status_of_The_Territories-6.svg.png

**Comment by softgrass** [comment]
The map used on Worldle is just the map recognized by the UN, mainly to avoid any political controversy because of how divided people are about what is and isn't Israel. They're just using the officially recognized map of Israel rather than Israel's version.

**Comment by Yaron-Ha** [comment]
> The map used on Worldle is just the map recognized by the UN, mainly to avoid any political controversy because of how divided people are about what is and isn't Israel. They're just using the officially recognized map of Israel rather than Israel's version.

Well, if you want to avoid political controversy around maps, you should highlight controversial areas with a marker to indicate controversy. You don't just completely omit the controversial parts.
