### ISSUE TITLE
Why not relative size of country?

### ISSUE THREAD

**Issue by SueMeyers** [teuteuf/worldle#83]
Since the proximity % and the distance provide similar information, why not substitute proximity % with a relative size comparison between the guess and the correct country?  Or at least have that as an alternative option?

**Comment by tgasnier** [comment]
+100 on this. Had the same idea.

**Comment by teuteuf** [comment]
Duplicate with this issue: https://github.com/teuteuf/worldle/issues/9

I might try to add it soon! :)
