### ISSUE TITLE
Custom Maps

### ISSUE THREAD

**Issue by PopularMMOsAntnyTheCoolGamer** [teuteuf/worldle#87]
Hi, I don't have much to say about this, so this will be really short. I think a custom maps option would be great.

**Comment by teuteuf** [comment]
Hello! :)

What do you mean by "custom maps"?

**Comment by PopularMMOsAntnyTheCoolGamer** [comment]
I mean like being able to like create your own worldle, like it gives you options to chose a country or territory, how many chances you get to guess it, if it shows distance or not, and things like that. Then it gives you a link to share the custom map. For example, you could make custom worldle where the country is lets just say Zambia, you have 3 tries to guess it, and it doesn't show the arrows and / or how far off you are.
