### ISSUE TITLE
Territories option, cities option, capital option, extra hard mode option.

### ISSUE THREAD

**Issue by PopularMMOsAntnyTheCoolGamer** [teuteuf/worldle#88]
Here are some more suggestions from me!

**Comment by teuteuf** [comment]
Hello!

Thanks for you suggestion, I'll continue to use the same list as possible answers/picks!
I have already a few idea to adapt difficulty (disabling arrows, distance, ...).

Have you already tried the no map or the rotate option in the settings? :)
