### ISSUE TITLE
country size difference

### ISSUE THREAD

**Issue by teuteuf** [teuteuf/worldle#9]
add an option to display the country size difference

**Comment by SDJFkusd3957ak** [comment]
Yes please! I recommend using the percentage as a size indicator rather than distance (since you already have the km distance and direction listed).

If the country I guess is 50% (or 200%j of the size of the actual country, that info will help a lot!

**Comment by teuteuf** [comment]
I've just collected each country area to change the way to pick daily worldle, so I should add this soon! :)

**Comment by clmacaulay** [comment]
Yes please!  Distance and percentage are now basically giving you the same information but if percentage was relative to country size that would be so much more useful!

**Comment by teuteuf** [comment]
I've added a a settings to replace proximity by size percent.

If the country you input is twice the size of the target: it will display 200%!
If the country you input is half the size of the target: it will display 50%...

**Comment by clmacaulay** [comment]
I think it still needs some work, India is definitely not the same size as Bahrain. 😉

**Comment by clmacaulay** [comment]
Sorry I understand now, it is not percent differential, it is percent of total!
