### ISSUE TITLE
Guernsey due east of Bermuda?

### ISSUE THREAD

**Issue by Violalover32086** [teuteuf/worldle#92]
![Screenshot_20220311-062542_Chrome](https://user-images.githubusercontent.com/101400753/157858655-af10f735-dcff-4ae9-9954-9c84a178ea65.jpg)

**Comment by joemamalolxd** [comment]
Well it is. What's the problem

**Comment by Violalover32086** [comment]
32 degrees latitude and 49 degrees latitude are due east of each other?

![Screenshot_20220311-082910_Chrome](https://user-images.githubusercontent.com/101400753/157877237-7af61211-da39-4d54-8791-de595aad1c8b.jpg)

**Comment by joemamalolxd** [comment]
2° longitude isn't east of -64° longitude?

**Comment by joemamalolxd** [comment]
Or we could just settle on Guernsey being north-east of Bermuda.

**Comment by Violalover32086** [comment]
Yes that's what I meant. Due east is Africa, not Europe. It should have showed the north-east arrow.
