### ISSUE TITLE
map error

### ISSUE THREAD

**Issue by a401skw** [teuteuf/worldle#94]
Terceira Island, which belongs to the Portuguese Azores, is incorrectly registered as Bouvet Island, a Norwegian territory.
![False Bouvet Island](https://user-images.githubusercontent.com/101417233/157909479-790efd1b-caf5-4ddb-a7c4-b3c316de4c2d.png)
![Terceira Island](https://user-images.githubusercontent.com/101417233/157909507-c4f087c7-65f8-4493-8ce5-f89c4caa6d63.jpg)

**Comment by teuteuf** [comment]
Damn, you're right... I'll try to fix it asap.

**Comment by teuteuf** [comment]
Thanks for reporting it!

**Comment by teuteuf** [comment]
If anyone could do a PR for this, it would be lovely! I have low access to internet until money... :/

The SVG image needs to be replaced by one with the same size (1024x1024px).

**Comment by teuteuf** [comment]
okay, finally I can fix it. on it! :)

**Comment by teuteuf** [comment]
Fixed! 🎉
